### ISSUE TITLE
Multiple definition of ptm_formats

### ISSUE THREAD

**Issue by NilsBrumm** [cceh/rti#3]
Hi, used your git earlier this year and it went great. Now I wanted to use it again and I got this error. Apparently the global variable ptm_formats exists multiple times in the components, which is why the error occurred. Did you maybe do a hard reset? Can you restore the executable version? 

Thank you!

**Comment by NilsBrumm** [comment]
![image](https://github.com/cceh/rti/assets/48394692/54d4641e-576c-4f9a-96e5-a83f84c286ba)

**Comment by MarcelloPerathoner** [comment]
gcc changed the default of -fcommon to -fno-common. As a quick fix you can add the -fcommon flag to the CFLAGS in the Makefile and clean your build dir before recompiling.
